apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gtkk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gtkk
    app.kubernetes.io/part-of: tkrw-pr714-0075-0044-app
  name: devfile-sample-gtkk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gtkk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gtkk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0044-tenant/tkrw-pr714-0075-0044-app/devfile-sample-gtkk@sha256:523ca7d511b7947335d6e85b2087ae77f7bb8db58de19b8b89dd23369ca8858a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
